spring.application.name=therapy

# Configura\u00E7\u00E3o do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/therapydb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura\u00E7\u00E3o JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Porta da aplica\u00E7\u00E3o
server.port=8080

# Configura\u00E7\u00E3o JWT
jwt.secret=AnyMultiplesKeysBiggestWithMoreThan32CharactersHere1234567890ABCdef!@$ 
jwt.expiration=3600000