spring.application.name=therapy
app.allowed-origins=http://localhost:4200
spring.datasource.url=jdbc:postgresql://localhost:5432/therapydb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8080
jwt.secret=455Y5LVYqVGtwOUFTtZsTC8DB5Rzr26J4LA5sx5YIOc=
jwt.expiration=3600000