spring.application.name=therapy

# Porta da aplicação (Render exige 10000)
server.port=${PORT:10000}

# Configuração do banco (via variável DATABASE_URL)
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configuração JWT
app.jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
